# Generated by Django 4.0.6 on 2023-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('key_values', models.CharField(choices=[('control', 'control'), ('experiment', 'experiment')], default=1, max_length=20, verbose_name='Key-values')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('key_value_id', models.BigIntegerField(verbose_name='Key-values ID')),
                ('country_id', models.IntegerField(verbose_name='Country ID')),
                ('total_code_served_count', models.IntegerField(verbose_name='Total code served count')),
                ('unfilled_impressions', models.IntegerField(verbose_name='Unfilled impressions')),
                ('total_impresions', models.IntegerField(verbose_name='Total impressions')),
                ('cpm_cpc_revenue', models.FloatField(verbose_name='Total CPM and CPC revenue ($)')),
                ('average_ecpm', models.FloatField(verbose_name='Total average eCPM ($)')),
                ('ad_server_impressiosn', models.IntegerField(verbose_name='Ad server impressions')),
                ('ad_server_average_ecpm', models.FloatField(verbose_name='Ad server average eCPM ($)')),
                ('ad_sever_cpm_cpc_revenue', models.FloatField(verbose_name='Ad server CPM and CPC revenue ($)')),
                ('ad_exchange_impressions', models.IntegerField(verbose_name='Ad Exchange impressions')),
                ('ad_exchange_revenue', models.FloatField(verbose_name='Ad Exchange revenue ($)')),
                ('ad_exchange_average_ecpm', models.FloatField(verbose_name='Ad Exchange average eCPM ($)')),
            ],
        ),
    ]
