# Generated by Django 4.0.6 on 2023-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertdata',
            name='extras',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
