# Generated by Django 4.0.6 on 2023-02-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_advertdata_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertdata',
            old_name='ad_server_impressiosn',
            new_name='ad_server_impressions',
        ),
    ]
